// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradutorHmmm.Data;

#nullable disable

namespace TradutorHmmm.Migrations
{
    [DbContext(typeof(TraducaoContext))]
    [Migration("20230813162530_traducao")]
    partial class traducao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TradutorHmmm.Models.Traducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Palavra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PalavraTraduzida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Traducaos");
                });
#pragma warning restore 612, 618
        }
    }
}
